
services:
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 1000000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1000000000
      KAFKA_RECEIVE_BUFFER_BYTES: 1000000000
      KAFKA_FETCH_MAX_BYTES: 1000000000
    networks:
      - log-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - log-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: log_db
    ports:
      - "5432:5432"
    networks:
      - log-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - log-network

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - log-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    networks:
      - log-network

  log-producer:
    build:
      context: ./log-producer
    environment:
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9093
    depends_on:
      - kafka
    networks:
      - log-network

networks:
  log-network:
    name: log-network