spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/log_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


