global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'log-analytics-system'
    static_configs:
      - targets:
          - 'log-producer:8081'
          - 'log-processor:8082'
          - 'log-api:8083'
