pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/master']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/SergTito/LogAnalizer.git',
                        credentialsId: 'github-token'
                    ]]
                ])
            }
        }

        stage('Check Code Style') {
            steps {
                sh 'mvn checkstyle:checkstyle' // Генерирует XML-отчет
                recordIssues tools: [checkStyle(pattern: '**/target/checkstyle-result.xml')]
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build Services') {
            parallel {
                stage('Build log-api') {
                    steps {
                        dir('log-api') {
                            sh 'mvn clean package'
                        }
                    }
                }
                stage('Build log-processor') {
                    steps {
                        dir('log-processor') {
                            sh 'mvn clean package'
                        }
                    }
                }
                stage('Build log-producer') {
                    steps {
                        dir('log-producer') {
                            sh 'mvn clean package'
                        }
                    }
                }
            }
        }
    }
}
