pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/master']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/SergTito/LogAnalizer.git',
                        credentialsId: 'github-token'
                    ]]
                ])
            }
        }
    }
}
