server:
  port: 8081
  address: 0.0.0.0

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092,kafka-2:9094
      bindings:
        logProducer-out-0:
          destination: ${log.topic.name} # Динамическое название топика через переменную
          content-type: application/json
          producer:
            use-native-encoding: true

  kafka:
    bootstrap-servers: kafka:9092,kafka-2:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enable-idempotence: true
      properties:
        max.in.flight.requests.per.connection: 5



logging:
  level:
    root: INFO
    com.example.logproducer: INFO

log:
  topic:
    name: default-logs-topic # Дефолтный топик, если имя сервиса неизвестно для тестов
