spring:
  cloud:
    stream:
      bindings:
        output:
          destination: logs-topic  # ???????? ??????
      kafka:
        binder:
          brokers: kafka:9093  # ????? Kafka (????????? "kafka", ??? ??? ??? ??? ??????? ? Docker)
          configuration:
            max.request.size: 1000000000  # ~1 ?? (????????? ? ??????????? Kafka)