spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/log_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true